# Generated by Django 4.2.15 on 2024-09-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecord',
            options={'permissions': (('fetch_records', 'fetch own records'), ('fetch_own_patients_records', 'fetch own patients records'), ('modify_own_patients_records', 'modify own patients records'))},
        ),
    ]
